# Calculate thermodynamic properties at a given temperature

In [1]:
from ThermoCR.QMthermo import qm_thermo

opt_freq_output_file_path = 'CPD.out'
thermo_result = qm_thermo(atom_coord_path=opt_freq_output_file_path, ee=-194.283781614283, T=298.15, P=101325)

======= Translation =======
q_t: 1.2720935150615787e+31
U_t: 3718.4365201799997
H_t: 6197.394200299999
Cv_t: 12.4716972
Cp_t: 20.786161999999997
S_t: 161.01710841383226
========= Rotation ========
q_r: 25106.61623016726
U_r: 3718.4365201799997
H_r: 3718.4365201799997
Cv_r: 12.4716972
Cp_r: 12.4716972
S_r: 96.70459793698586
======== Vibration ========
q_v_bot: 6.629114240928768e-43
q_v_0: 1.618097452351035
zpe: 241948.79449427157
U_v_0_T: 3475.28185277795
H_v_0_T: 3475.28185277795
U_v: 245424.07634704956
H_v: 245424.07634704956
Cv_v: 40.50361042866027
Cp_v: 40.50361042866027
S_v: 15.657497339217844
======== Electron excitation ========
q_e: 1.0
U_e: 0.0
H_e: 0.0
Cv_e: 0.0
Cp_e: 0.0
S_e: 0.0
========== Total ==========
Ignore contribution of trans and rot? False
q(V=0): 5.167873768255353e+35
q(bot): 2.1172040993382425e-07
Cv_tot: 65.44700482866027 J/mol/K
Cp_tot: 73.76146962866027 J/mol/K
S_tot: 273.379203690036 J/mol/K
ZPE: 241948.79449427157 J/mol
U_corr: 252860.94938740955 J/mol
H_corr: 255339.90706752957 J/mol
G_corr: 173831.89748734533 J/mol
EE: -510092068.62829995 J/mol -194.283781614283 a.u.
Sum of electronic energy and ZPE, namely U/H/G at 0 K: -509850119.8338057 J/mol -194.1916281979835 a.u.
Sum of electronic energy and thermal correction to U: -509839207.6789125  J/mol -194.18747197825653 a.u.
Sum of electronic energy and thermal correction to H: -509836728.7212324  J/mol -194.18652779327078 a.u.
Sum of electronic energy and thermal correction to G: -509918236.7308126  J/mol -194.2175725503 a.u.

# Calculate thermodynamic properties at a series of temperatures

In [4]:
from ThermoCR.QMthermo import qm_thermo_scan

opt_freq_output_file_path = 'CPD.out'
T = range(200, 750, 50)
thermo_scan_df = qm_thermo_scan(atom_coord_path=opt_freq_output_file_path, ee=-194.283781614283, T=T, P=[101325], out_path='QMthermoScan_CPD.xlsx')
thermo_scan_df

,T/K,P/Pa,q_tot_v_0,q_tot_bot,Cv/(J/mol/K),Cp/(J/mol/K),S/(J/mol/K),zpe/(J/mol),U_corr/(J/mol),H_corr/(J/mol),G_corr/(J/mol),ee/(J/mol),U/(J/mol),H/(J/mol),G/(J/mol)
0,200,101325,7.406564e+34,4.790467e-29,40.507634,48.822099,249.453223,241948.794494,247713.976117,249376.869077,199486.224553,-5.100921e+08,-5.098444e+08,-5.098427e+08,-5.098926e+08
1,250,101325,2.094113e+35,5.883137e-16,52.412891,60.727356,261.580820,241948.794494,250026.764170,252105.380370,186710.175399,-5.100921e+08,-5.098420e+08,-5.098400e+08,-5.099054e+08
2,300,101325,5.343831e+35,3.996626e-07,65.959727,74.274192,273.837058,241948.794494,252982.500568,255476.840008,173325.722497,-5.100921e+08,-5.098391e+08,-5.098366e+08,-5.099187e+08
3,350,101325,1.290645e+36,1.006168e+00,79.749363,88.063828,286.325822,241948.794494,256626.471133,259536.533813,159322.496053,-5.100921e+08,-5.098354e+08,-5.098325e+08,-5.099327e+08
4,400,101325,3.020576e+36,7.681930e+04,92.895797,101.210262,298.953585,241948.794494,260946.453549,264272.239469,144690.805385,-5.100921e+08,-5.098311e+08,-5.098278e+08,-5.099474e+08
5,450,101325,6.928976e+36,5.709037e+08,104.977698,113.292163,311.583414,241948.794494,265898.141902,269639.651062,129427.114634,-5.100921e+08,-5.098262e+08,-5.098224e+08,-5.099626e+08
6,500,101325,1.566168e+37,8.301235e+11,115.877897,124.192362,324.094421,241948.794494,271424.441053,275581.673453,113534.463152,-5.100921e+08,-5.098206e+08,-5.098165e+08,-5.099785e+08
7,550,101325,3.495887e+37,3.678343e+14,125.642525,133.956990,336.397771,241948.794494,277466.969312,282039.924952,97021.150887,-5.100921e+08,-5.098146e+08,-5.098100e+08,-5.099950e+08
8,600,101325,7.711671e+37,6.669125e+16,134.387658,142.702123,348.435408,241948.794494,283971.694106,288960.372986,79899.128047,-5.100921e+08,-5.098081e+08,-5.098031e+08,-5.100122e+08
9,650,101325,1.681328e+38,6.064706e+18,142.246751,150.561216,360.173482,241948.794494,290890.973179,296295.375299,62182.612284,-5.100921e+08,-5.098012e+08,-5.097958e+08,-5.100299e+08
10,700,101325,3.622485e+38,3.198441e+20,149.345350,157.659814,371.595392,241948.794494,298183.704512,304003.829872,43887.055584,-5.100921e+08,-5.097939e+08,-5.097881e+08,-5.100482e+08

# Fit the thermodynamic quantities at different temperatures using the NASA7 model

In [6]:
from ThermoCR.QMthermo.fit_thermo import fit_thermo_model

fit_result = fit_thermo_model(data_path='QMthermoScan_CPD.xlsx', name='CPD', model_type='NASA7', output_dir='fit_NASA7_results')

--------------------------------------------------
 Cp_T
 r2: 1.0
 mse: 0.017
 mae: 0.116
 mape: 0.001
--------------------------------------------------
 H_T
 r2: 1.0
 mse: 25.846
 mae: 4.49
 mape: 0.0
--------------------------------------------------
 S_T
 r2: 1.0
 mse: 0.0
 mae: 0.011
 mape: 0.0

# Calculate the reaction rate constant of a chemical reaction at a given temperature
2CPD -> DCPD

In [9]:
from ThermoCR.QMthermo.qm_thermo import qm_thermo
from ThermoCR.QMkinetics.qm_kinetics import k_TST
from ThermoCR.tools import read_imaginary_vib

CPD_thermo = qm_thermo(atom_coord_path='CPD.out', ee=-194.283781614283, T=298.15, P=100000, verbose=False)
TS_thermo = qm_thermo(atom_coord_path='TS_CPD_DCPD.out', ee=-388.546183691360, T=298.15, P=100000, verbose=False)
DCPD_thermo = qm_thermo(atom_coord_path='DCPD.out', ee=-388.612084245544, T=298.15, P=100000, verbose=False)

delta_G = TS_thermo['G/(J/mol)'] - 2 * CPD_thermo['G/(J/mol)']
imaginary_freq = read_imaginary_vib('TS_CPD_DCPD.out')

k = k_TST(delta_G=delta_G, delta_n=1, tunnelling_effect='wigner', imaginary_freq=imaginary_freq, T=298.15, sigma=1)
print(f'k is {k} (molecule/m^3)^(-delta_n) * s^-1')

k is 9.218793693728515e-34 (molecule/m^3)^(-delta_n) * s^-1

# Calculate the reaction rate constants at a series of temperatures

In [12]:
from ThermoCR.QMthermo.qm_thermo import qm_thermo_scan
from ThermoCR.QMkinetics.qm_kinetics import k_TST_scan
from ThermoCR.tools import read_imaginary_vib

T = range(200, 750, 50)
imaginary_freq = read_imaginary_vib('TS_CPD_DCPD.out')
CPD_thermo_scan = qm_thermo_scan(atom_coord_path='CPD.out', ee=-194.283781614283, T=T, P=[100000], out_path='QMthermoScan_CPD.xlsx')
TS_thermo_scan = qm_thermo_scan(atom_coord_path='TS_CPD_DCPD.out', ee=-388.546183691360, T=T, P=[100000], out_path='QMthermoScan_TS.xlsx')
DCPD_thermo_scan = qm_thermo_scan(atom_coord_path='DCPD.out', ee=-388.612084245544, T=T, P=[100000], out_path='QMthermoScan_DCPD.xlsx')

k_scan_df = k_TST_scan(thermo_ts_path='QMthermoScan_TS.xlsx', 
                    thermo_r1_path='QMthermoScan_CPD.xlsx', thermo_r2_path='QMthermoScan_CPD.xlsx', 
                    thermo_p_path='QMthermoScan_DCPD.xlsx',
                    tunnelling_effect='eckart',
                    imaginary_freq=imaginary_freq, sigma=1, out_path='TST_scan_2CPD_to_DCPD.xlsx')

k_scan_df

    T/K             k
0   200  2.995841e-39
1   250  6.244449e-36
2   300  1.108807e-33
3   350  4.752671e-32
4   400  8.321908e-31
5   450  7.989584e-30
6   500  5.022545e-29
7   550  2.316056e-28
8   600  8.449632e-28
9   650  2.570403e-27
10  700  6.776966e-27

# Fit the rate constants at different temperatures using the Arrhenius equation

In [13]:
from ThermoCR.QMkinetics.fit_kinetics import fit_kinetics_model

fit_result = fit_kinetics_model(model_type='Arrhenius', data_path='TST_scan_2CPD_to_DCPD.xlsx', r_name_list=['CPD', 'CPD'],
                                p_name_list=['DCPD'], output_dir='fit_Arrhenius_result',)

Fitted parameters:
(np.float64(1.0631598419814308e-30), np.float64(57408.7680557581), np.float64(2.8428707621407554))
--------------------------------------------------
 k
 r2: 1.0
 mse: 0.0
 mae: 0.0
 mape: 0.0

# Calculate the rate constants at a series of temperatures based on VTST

In [16]:
import pandas as pd
from ThermoCR.QMthermo.qm_thermo import qm_thermo_scan
from ThermoCR.QMkinetics.qm_kinetics import k_VTST_scan
from ThermoCR.tools import read_imaginary_vib

T = range(200, 750, 50)
imaginary_freq = read_imaginary_vib('TS_CPD_DCPD.out')
IRC_SP_df = pd.read_excel('IRC.xlsx')

IRC_thermo_scans = [
    qm_thermo_scan(atom_coord_path=f'./IRC_freq/{name}_freq.out', ee=sp, T=T, P=[100000], out_path=f'QMthermoScan_{name}.xlsx') 
    for name, sp in zip(IRC_SP_df['name'], IRC_SP_df['wB97Mp2'])
]

CPD_thermo_scan = qm_thermo_scan(atom_coord_path='CPD.out', ee=-194.283781614283, T=T, P=[100000], out_path='QMthermoScan_CPD.xlsx')
TS_thermo_scan = qm_thermo_scan(atom_coord_path='TS_CPD_DCPD.out', ee=-388.546183691360, T=T, P=[100000], out_path='QMthermoScan_TS.xlsx')
DCPD_thermo_scan = qm_thermo_scan(atom_coord_path='DCPD.out', ee=-388.612084245544, T=T, P=[100000], out_path='QMthermoScan_DCPD.xlsx')

k_vtst_scan = k_VTST_scan(
    thermo_irc_path_list=[f'QMthermoScan_{name}.xlsx' for name in IRC_SP_df['name']],
    thermo_r1_path='QMthermoScan_CPD.xlsx', thermo_r2_path='QMthermoScan_CPD.xlsx', 
    thermo_p_path='QMthermoScan_DCPD.xlsx',
    tunnelling_effect='eckart',
    imaginary_freq=imaginary_freq, sigma=1, out_path='VTST_scan_2CPD_to_DCPD.xlsx'
)

k_vtst_scan

array([2.85385316e-39, 5.71024464e-36, 7.44372442e-34, 2.49444544e-32,
       3.56311486e-31, 2.87719362e-30, 1.55645964e-29, 6.28726949e-29,
       2.03801006e-28, 5.57287132e-28, 1.33378047e-27])